### ISSUE TITLE
A question about comfiling

### ISSUE THREAD

**Issue by meijuanwang** [Raymw/Federated-XGBoost#2]
Hi,
  I modified the two files-"param.h"and "updater_histmaker.cc" of XGBoost, and compiled. There are some problems. You only modify this two file?
![image](https://user-images.githubusercontent.com/65224044/81671645-c5e18180-947b-11ea-8dba-dfc1c568ff81.png)

**Comment by Raymw** [comment]
Hi, 
yes only those two files are modified. The problem probably is caused by the version conflict of XGBoost. You can try other versions like 0.90 to see if it works.

**Comment by meijuanwang** [comment]
Hi
  I tried version 0.90, but a new problem has arisen. It looks like he problem is in the file "update_histmaker" 
 I use a virtual machine and the operating system is centos 7.
![image](https://user-images.githubusercontent.com/65224044/81763216-4d250880-9501-11ea-8a9a-e9c4ae310f56.png)

**Comment by Raymw** [comment]
Hi
 "has no member named Getbatches"  Getbatches is their own function. They changed it in later version i guess. Cuz when i was making changes to the code, the version of xgboost is earlier than this.
However, one of my friends put all these changes manually into the new version' file and it also works well in the 0.9 version. also remember to recompile it after adding changes and also do "make" in Rabit as i mentioned in "readme".
Thanks!

**Comment by meijuanwang** [comment]
Hi,
   Does your friend download xgboost through ‘ git clone’? For the Rabit part, I didn't find the file "submit.py" in /xgboost/rabit . I put changes into the 0.9 version,  and do "make", is that right?
Thanks!

**Comment by Raymw** [comment]
submit.py is in "/xgboost/dmlc-core/tracker/dmlc_tracker/submit.py" and you also need to recompile the XGBoost so the changes can make sense

**Comment by meijuanwang** [comment]
Hi,
  I have solved my problem,and I use 0.9 version.  some changes also do in "updater_histmaker.cc". In line 22 and 31, you can mentioned it in "readme"
 At first, I exchanged the two files in /xgboost/src/tree, so I meeted some problems.  
 I have another question, what should I change in "submit.py"?

**Comment by Raymw** [comment]
Thanks !
for submit.py the changes are because there exist some bugs in earlier version about "kubernetes" while running. So I comment it. But I am not sure if they have fixed the bug in the latest version and you may try both !

**Comment by meijuanwang** [comment]
Thanks! My problem has been solved! I used 0.9version xgboost, and didn't motify any code in 'submit.py'. May be the bug has been fixed!

**Comment by qinleiyong** [comment]
> Hi
> I tried version 0.90, but a new problem has arisen. It looks like he problem is in the file "update_histmaker"
> I use a virtual machine and the operating system is centos 7.
> ![image](https://user-images.githubusercontent.com/65224044/81763216-4d250880-9501-11ea-8a9a-e9c4ae310f56.png)

I met the same problem. How did you solve it?

**Comment by Raymw** [comment]
Hi, I suggest that you can put all these changes manually into the version 0.9's file. Thanks!

**Comment by Jaap-Meerhof** [comment]
Is it possible that you give the changes such that your research can be reproduced?
